COMMODITIES_SEED = [
    {
        "id": "c-tomato",
        "name": "Tomato",
        "category": "Vegetables",
        "image_url": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 94.5,
        "default_fat_pct": 0.2,
        "default_ph": 4.3,
        "respiration_rate": "High",
        "oxygen_sensitivity": "Medium",
        "light_sensitivity": "Medium",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "High",
        "description": "Perishable climacteric produce requiring controlled gas exchange and high humidity maintenance without water accumulation."
    },
    {
        "id": "c-apple",
        "name": "Apple",
        "category": "Fruits",
        "image_url": "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 85.5,
        "default_fat_pct": 0.2,
        "default_ph": 3.8,
        "respiration_rate": "Medium",
        "oxygen_sensitivity": "Medium",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "Medium",
        "texture_sensitivity": "Medium",
        "description": "Moderately high respiration rate fruit needing impact protection and controlled CO2/O2 exchange."
    },
    {
        "id": "c-banana",
        "name": "Banana",
        "category": "Fruits",
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 75.0,
        "default_fat_pct": 0.3,
        "default_ph": 5.1,
        "respiration_rate": "High",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "Medium",
        "texture_sensitivity": "High",
        "description": "Ethylene-sensitive climacteric fruit susceptible to chill injury and rapid ripening under poor gas control."
    },
    {
        "id": "c-mango",
        "name": "Mango",
        "category": "Fruits",
        "image_url": "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 83.0,
        "default_fat_pct": 0.4,
        "default_ph": 4.5,
        "respiration_rate": "High",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "Medium",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "High",
        "description": "Tropical fruit with high metabolic activity requiring gentle cushioning and MAP optimization."
    },
    {
        "id": "c-potato",
        "name": "Potato",
        "category": "Vegetables",
        "image_url": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 79.0,
        "default_fat_pct": 0.1,
        "default_ph": 5.8,
        "respiration_rate": "Low",
        "oxygen_sensitivity": "Low",
        "light_sensitivity": "High",
        "microbial_sensitivity": "Medium",
        "texture_sensitivity": "Medium",
        "description": "Light-sensitive root vegetable prone to greening (solanine synthesis) and sprouting under moisture."
    },
    {
        "id": "c-rice",
        "name": "Rice",
        "category": "Grains",
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 12.0,
        "default_fat_pct": 0.6,
        "default_ph": 6.5,
        "respiration_rate": "None",
        "oxygen_sensitivity": "Low",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "Low",
        "texture_sensitivity": "Low",
        "description": "Dry staple commodity sensitive to moisture ingress, insect infestation, and bag tearing during transport."
    },
    {
        "id": "c-wheat",
        "name": "Wheat Grain",
        "category": "Grains",
        "image_url": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 11.5,
        "default_fat_pct": 1.5,
        "default_ph": 6.4,
        "respiration_rate": "None",
        "oxygen_sensitivity": "Low",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "Low",
        "texture_sensitivity": "Low",
        "description": "Bulk grain requiring sturdy moisture barrier and puncture-resistant bulk flexible or woven containers."
    },
    {
        "id": "c-chips",
        "name": "Potato Chips",
        "category": "Snacks",
        "image_url": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 2.0,
        "default_fat_pct": 35.0,
        "default_ph": 6.0,
        "respiration_rate": "None",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "High",
        "microbial_sensitivity": "Low",
        "texture_sensitivity": "High",
        "description": "Fried snack food highly vulnerable to rancidity (fat oxidation), crispness loss (moisture pickup), and physical crushing."
    },
    {
        "id": "c-biscuits",
        "name": "Biscuits / Cookies",
        "category": "Bakery",
        "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 3.0,
        "default_fat_pct": 18.0,
        "default_ph": 6.8,
        "respiration_rate": "None",
        "oxygen_sensitivity": "Medium",
        "light_sensitivity": "Medium",
        "microbial_sensitivity": "Low",
        "texture_sensitivity": "High",
        "description": "Crisp baked product requiring grease resistance, moisture vapor barrier, and mechanical structural protection."
    },
    {
        "id": "c-milk",
        "name": "Fresh Pasteurized Milk",
        "category": "Dairy",
        "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 87.5,
        "default_fat_pct": 3.5,
        "default_ph": 6.7,
        "respiration_rate": "None",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "High",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "Low",
        "description": "Highly perishable liquid dairy susceptible to light-induced off-flavors, oxidation, and rapid bacterial spoilage."
    },
    {
        "id": "c-cheese",
        "name": "Cheddar Cheese",
        "category": "Dairy",
        "image_url": "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 37.0,
        "default_fat_pct": 33.0,
        "default_ph": 5.2,
        "respiration_rate": "Low",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "High",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "Medium",
        "description": "High-fat dairy product requiring tight vacuum or gas flush (low O2) packaging to prevent mold growth and lipid oxidation."
    },
    {
        "id": "c-bread",
        "name": "Sliced White Bread",
        "category": "Bakery",
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 36.0,
        "default_fat_pct": 3.0,
        "default_ph": 5.5,
        "respiration_rate": "None",
        "oxygen_sensitivity": "Medium",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "High",
        "description": "Short shelf-life bakery item prone to staling (starch retrogradation) and mold infestation if moisture escapes or accumulates."
    },
    {
        "id": "c-frozenpeas",
        "name": "Frozen Green Peas",
        "category": "Frozen Foods",
        "image_url": "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 78.0,
        "default_fat_pct": 0.4,
        "default_ph": 6.2,
        "respiration_rate": "None",
        "oxygen_sensitivity": "Medium",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "Low",
        "texture_sensitivity": "Medium",
        "description": "Sub-zero commodity requiring low-temperature flexibility, puncture resistance, and water vapor lock to avoid freezer burn."
    },
    {
        "id": "c-fish",
        "name": "Fresh Fish Fillet",
        "category": "Seafood",
        "image_url": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 75.0,
        "default_fat_pct": 5.0,
        "default_ph": 6.6,
        "respiration_rate": "None",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "Medium",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "High",
        "description": "Ultra-perishable seafood prone to enzymatic degradation, odor release, and bacterial growth under aerobic chilled conditions."
    },
    {
        "id": "c-chicken",
        "name": "Fresh Raw Chicken",
        "category": "Meat",
        "image_url": "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&q=80&w=600",
        "default_moisture_pct": 74.0,
        "default_fat_pct": 12.0,
        "default_ph": 6.0,
        "respiration_rate": "None",
        "oxygen_sensitivity": "High",
        "light_sensitivity": "Low",
        "microbial_sensitivity": "High",
        "texture_sensitivity": "Medium",
        "description": "High moisture & protein meat commodity demanding leak-proof hermetic seals, high barrier properties, and MAP or vacuum skin packaging."
    }
]

MATERIALS_SEED = [
    {
        "id": "m-ldpe",
        "name": "Low-Density Polyethylene (LDPE)",
        "category": "Flexible Plastic",
        "typical_applications": ["Produce bags", "Bread wrappers", "Milk pouch inner layer", "Squeeze bottles"],
        "moisture_barrier": "High",
        "oxygen_barrier": "Low",
        "co2_permeability": "High",
        "otr_range": "High (2000-4000 cc/m²/24h)",
        "wvtr_range": "Low-Moderate (10-15 g/m²/24h)",
        "mechanical_strength": "Moderate",
        "sealability": "Excellent",
        "flexibility": "Flexible",
        "transparency": "Transparent to Translucent",
        "light_barrier": "Low",
        "temp_compatibility": "Chilled / Ambient (-40°C to 80°C)",
        "recyclability": "Recyclable (RIC #4)",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "Low",
        "food_compatibility": ["Produce", "Bakery", "Poultry (seal layer)", "Grains"],
        "advantages": ["Excellent heat sealability", "High toughness and flexibility", "Outstanding water moisture barrier", "Low cost"],
        "limitations": ["Poor oxygen barrier", "Poor aroma and oil barrier", "Low tensile strength"],
        "typical_structures": ["LDPE Monolayer", "PET/LDPE", "BOPP/LDPE"],
        "data_source": "Standard Polymer Handbook for Packaging"
    },
    {
        "id": "m-hdpe",
        "name": "High-Density Polyethylene (HDPE)",
        "category": "Rigid / Flexible Plastic",
        "typical_applications": ["Milk jugs", "Rigid crates", "Grain sacks", "Cereal box liners"],
        "moisture_barrier": "Very High",
        "oxygen_barrier": "Low",
        "co2_permeability": "Moderate",
        "otr_range": "Moderate-High (1000-2000 cc/m²/24h)",
        "wvtr_range": "Low (3-6 g/m²/24h)",
        "mechanical_strength": "High",
        "sealability": "Good",
        "flexibility": "Semi-rigid",
        "transparency": "Translucent",
        "light_barrier": "Moderate",
        "temp_compatibility": "Frozen / Chilled / Ambient (-50°C to 110°C)",
        "recyclability": "Recyclable (RIC #2)",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "Low",
        "food_compatibility": ["Milk", "Bulk Grains", "Juices", "Frozen produce"],
        "advantages": ["High stiffness and impact strength", "Superior moisture barrier", "Good chemical resistance", "High recyclability"],
        "limitations": ["Opaque/cloudy appearance", "Low gas barrier without barrier layers"],
        "typical_structures": ["HDPE Bottles", "HDPE Monolayer Film"],
        "data_source": "Packaging Technology Databook"
    },
    {
        "id": "m-pet",
        "name": "Polyethylene Terephthalate (PET)",
        "category": "Rigid / Flexible Film",
        "typical_applications": ["Beverage bottles", "Laminate outer printing film", "Thermoformed trays", "Clamshells"],
        "moisture_barrier": "Moderate",
        "oxygen_barrier": "Moderate",
        "co2_permeability": "Low",
        "otr_range": "Moderate (50-100 cc/m²/24h)",
        "wvtr_range": "Moderate (15-25 g/m²/24h)",
        "mechanical_strength": "Very High",
        "sealability": "Fair (Needs PE sealing layer)",
        "flexibility": "Flexible to Rigid",
        "transparency": "Transparent",
        "light_barrier": "Low (Clear) / High (Amber/Pigmented)",
        "temp_compatibility": "Chilled / Ambient / Retort (-40°C to 150°C)",
        "recyclability": "Recyclable (RIC #1)",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "Medium",
        "food_compatibility": ["Snacks (laminate)", "Beverages", "Meat trays", "Sauces"],
        "advantages": ["Crystal clear optics", "High tensile strength and dimensional stability", "Good gas barrier for carbonation", "Excellent thermal range"],
        "limitations": ["Requires heat-sealable secondary layer for pouches", "Higher density than polyolefins"],
        "typical_structures": ["PET Bottles", "PET/PE", "PET/Al/PE"],
        "data_source": "Polymer Engineering Guide"
    },
    {
        "id": "m-bopp",
        "name": "Biaxially Oriented Polypropylene (BOPP)",
        "category": "Flexible Film",
        "typical_applications": ["Chip bags", "Confectionery wraps", "Biscuit inner/outer film", "Label films"],
        "moisture_barrier": "High",
        "oxygen_barrier": "Low-Moderate",
        "co2_permeability": "Moderate",
        "otr_range": "Moderate-High (1500-2000 cc/m²/24h)",
        "wvtr_range": "Low (4-7 g/m²/24h)",
        "mechanical_strength": "High",
        "sealability": "Good (Coated/Coextruded)",
        "flexibility": "Flexible",
        "transparency": "Transparent",
        "light_barrier": "Low (Clear) / Complete (Metallized)",
        "temp_compatibility": "Ambient / Chilled (-10°C to 100°C)",
        "recyclability": "Recyclable (RIC #5)",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "Low-Medium",
        "food_compatibility": ["Potato Chips", "Biscuits", "Dry Snacks", "Pasta"],
        "advantages": ["Excellent moisture barrier", "High clarity and gloss", "Good stiffness and slip properties"],
        "limitations": ["Poor low-temperature impact (brittle at sub-zero)", "Low O2 barrier unless metallized"],
        "typical_structures": ["BOPP/CPP", "BOPP/Met-BOPP/PE"],
        "data_source": "Flexible Packaging Association Handbook"
    },
    {
        "id": "m-al-foil",
        "name": "Aluminium Foil Laminate",
        "category": "Laminate Barrier",
        "typical_applications": ["Retort pouches", "Coffee bags", "Potato chip laminates", "Pharmaceutical blister packs"],
        "moisture_barrier": "Very High (Absolute at >7µm)",
        "oxygen_barrier": "Very High (Absolute at >7µm)",
        "co2_permeability": "Very High Barrier",
        "otr_range": "Ultra-Low (<0.1 cc/m²/24h)",
        "wvtr_range": "Ultra-Low (<0.1 g/m²/24h)",
        "mechanical_strength": "High (when laminated)",
        "sealability": "Depends on inner layer (PE/CPP)",
        "flexibility": "Flexible",
        "transparency": "Opaque",
        "light_barrier": "Complete (100%)",
        "temp_compatibility": "Retort / Frozen / Ambient (-50°C to 250°C)",
        "recyclability": "Requires Delamination / Special Facilities",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "High",
        "food_compatibility": ["High-fat snacks", "Coffee", "Ready-to-Eat curries", "Powdered milk"],
        "advantages": ["100% barrier against light, oxygen, water vapor, and aromas", "Extreme shelf-life extension"],
        "limitations": ["Higher cost", "Prone to flex-cracking if pinholed", "Non-transparent", "Microwave unsafe"],
        "typical_structures": ["PET/Aluminium/PE", "PET/Aluminium/CPP"],
        "data_source": "Aluminium Foil Packaging Council Specifications"
    },
    {
        "id": "m-paper-pe",
        "name": "Paper-PE Laminate",
        "category": "Paper-Based Packaging",
        "typical_applications": ["Sugar packets", "Dry food bags", "Flour bags", "Eco pouches"],
        "moisture_barrier": "Moderate",
        "oxygen_barrier": "Low",
        "co2_permeability": "High",
        "otr_range": "High",
        "wvtr_range": "Moderate (10-20 g/m²/24h)",
        "mechanical_strength": "Moderate-High",
        "sealability": "Good",
        "flexibility": "Semi-flexible",
        "transparency": "Opaque",
        "light_barrier": "High",
        "temp_compatibility": "Ambient (-10°C to 80°C)",
        "recyclability": "Paper-Recyclable if PE < 15%",
        "biodegradability": "Partially Biodegradable",
        "relative_cost": "Medium",
        "food_compatibility": ["Dry Grains", "Flour", "Biscuits", "Bakery items"],
        "advantages": ["Natural tactile premium feel", "Renewable fiber substrate", "Light protection"],
        "limitations": ["Higher weight", "Moderate moisture barrier", "Tear prone if wet"],
        "typical_structures": ["Kraft Paper/PE", "Paper/PE/Al/PE"],
        "data_source": "Sustainable Packaging Research Network"
    },
    {
        "id": "m-pla-pbat",
        "name": "PLA / PBAT Biodegradable Film",
        "category": "Bio-based / Compostable",
        "typical_applications": ["Organic produce bags", "Compostable pouches", "Short shelf-life snack bags"],
        "moisture_barrier": "Low-Moderate",
        "oxygen_barrier": "Moderate",
        "co2_permeability": "High",
        "otr_range": "Moderate (200-500 cc/m²/24h)",
        "wvtr_range": "Moderate-High (40-80 g/m²/24h)",
        "mechanical_strength": "Moderate",
        "sealability": "Good",
        "flexibility": "Flexible",
        "transparency": "Translucent to Clear",
        "light_barrier": "Low",
        "temp_compatibility": "Ambient / Chilled (0°C to 50°C)",
        "recyclability": "Industrial Composting (EN 13432)",
        "biodegradability": "Compostable",
        "relative_cost": "High",
        "food_compatibility": ["Fresh produce", "Bakery", "Dry organic grains"],
        "advantages": ["Derived from renewable corn starch / bio-resins", "Zero persistent microplastics", "Good gas exchange for produce"],
        "limitations": ["Higher cost", "Lower moisture barrier", "Degrades in hot humid storage"],
        "typical_structures": ["PLA Monolayer", "PLA/PBAT Blend"],
        "data_source": "European Bioplastics Standard Data"
    },
    {
        "id": "m-microperf-pe",
        "name": "Micro-Perforated PE / PP Film",
        "category": "Breathable Produce Film",
        "typical_applications": ["Fresh tomato punnet wrap", "Berry bags", "Mushroom packaging", "Cut salad MAP"],
        "moisture_barrier": "Controlled",
        "oxygen_barrier": "Controlled Breathable",
        "co2_permeability": "Controlled High Exchange",
        "otr_range": "Engineered Breathable (5000-50000+ cc/m²/24h)",
        "wvtr_range": "Engineered Vapor Release",
        "mechanical_strength": "Moderate",
        "sealability": "Excellent",
        "flexibility": "Flexible",
        "transparency": "Transparent",
        "light_barrier": "Low",
        "temp_compatibility": "Chilled (0°C to 15°C)",
        "recyclability": "Recyclable (RIC #4 / #5)",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "Medium",
        "food_compatibility": ["Tomatoes", "Bananas", "Mangos", "Fresh Berries", "Cut Salads"],
        "advantages": ["Prevents anaerobiosis and off-odors in high respiration produce", "Eliminates moisture condensation / fogging"],
        "limitations": ["Unsuitable for oxygen-sensitive fried/fatty foods", "Not airtight"],
        "typical_structures": ["Laser Micro-Perforated LDPE", "Micro-Perforated PP"],
        "data_source": "Postharvest Technology & Packaging Guide"
    },
    {
        "id": "m-evoh-pe",
        "name": "EVOH-Laminated PE (High Oxygen Barrier)",
        "category": "High Barrier Polymer Laminate",
        "typical_applications": ["Fresh meat MAP trays", "Cheese vacuum pouches", "Processed chicken barrier bags"],
        "moisture_barrier": "High",
        "oxygen_barrier": "Very High",
        "co2_permeability": "Very Low",
        "otr_range": "Ultra-Low (0.5-5 cc/m²/24h)",
        "wvtr_range": "Low (2-5 g/m²/24h)",
        "mechanical_strength": "High",
        "sealability": "Excellent",
        "flexibility": "Flexible / Thermoformable",
        "transparency": "Transparent",
        "light_barrier": "Low (Clear) / Moderate",
        "temp_compatibility": "Chilled / Frozen (-30°C to 90°C)",
        "recyclability": "Monolithically Recyclable if EVOH < 5%",
        "biodegradability": "Non-biodegradable",
        "relative_cost": "High",
        "food_compatibility": ["Raw Chicken", "Fresh Meat", "Cheese", "Processed Seafood"],
        "advantages": ["Crystal clear transparent ultra-high oxygen barrier", "Retains MAP gas flush atmosphere"],
        "limitations": ["EVOH moisture sensitive if unprotected by outer PE layers", "Higher cost"],
        "typical_structures": ["PE/EVOH/PE", "PET/EVOH/PE"],
        "data_source": "Barrier Plastics Databook"
    }
]

STRUCTURES_SEED = [
    {
        "id": "s-pet-ldpe",
        "code_name": "PET / LDPE",
        "layer_composition": ["12µm PET (Outer Print)", "50µm LDPE (Inner Heat Seal)"],
        "barrier_level": "Moderate O2 / High Moisture",
        "sealability": "Excellent",
        "mechanical_strength": "High",
        "recyclability": "Multi-material (Requires specialized recycling)",
        "cost_category": "Medium",
        "temp_suitability": "Ambient / Chilled",
        "typical_applications": ["Biscuits", "Dry Powders", "Frozen Vegetables", "Detergents"],
        "description": "Versatile two-ply laminate combining glossy printable PET tensile strength with heat-sealable LDPE moisture protection."
    },
    {
        "id": "s-pet-al-pe",
        "code_name": "PET / Aluminium Foil / PE",
        "layer_composition": ["12µm PET", "7µm Aluminium Foil", "50µm LDPE"],
        "barrier_level": "Ultra-High 100% O2, Moisture & Light Barrier",
        "sealability": "Excellent",
        "mechanical_strength": "Very High",
        "recyclability": "Non-recyclable in standard streams",
        "cost_category": "High",
        "temp_suitability": "Ambient / Retortable / Frozen",
        "typical_applications": ["Potato Chips", "Coffee", "Spices", "Milk Powder", "Ready-to-Eat Meals"],
        "description": "Gold-standard high-barrier foil laminate delivering maximum protection against oxidation, crispness loss, and light degradation."
    },
    {
        "id": "s-bopp-cpp",
        "code_name": "BOPP / CPP (Monomaterial PP)",
        "layer_composition": ["20µm BOPP", "30µm Cast PP (CPP)"],
        "barrier_level": "High Moisture / Moderate O2",
        "sealability": "Good",
        "mechanical_strength": "High",
        "recyclability": "100% Monomaterial PP Recyclable (RIC #5)",
        "cost_category": "Low-Medium",
        "temp_suitability": "Ambient",
        "typical_applications": ["Pasta", "Confectionery", "Bakery Wraps", "Dry Snacks"],
        "description": "Fully recyclable mono-polypropylene structure providing high optical clarity and moisture barrier."
    },
    {
        "id": "s-microperf-pe",
        "code_name": "Micro-Perforated LDPE Monolayer",
        "layer_composition": ["35µm Laser-Perforated LDPE"],
        "barrier_level": "Controlled Breathable Gas Permeability",
        "sealability": "Excellent",
        "mechanical_strength": "Moderate",
        "recyclability": "100% Recyclable LDPE (RIC #4)",
        "cost_category": "Low",
        "temp_suitability": "Chilled / Ambient",
        "typical_applications": ["Tomatoes", "Bananas", "Fresh Fruits & Cut Produce"],
        "description": "Breathable film engineered with micro-perforations to maintain optimum O2/CO2 equilibrium for living produce."
    },
    {
        "id": "s-evoh-pe",
        "code_name": "PE / EVOH / PE Coex",
        "layer_composition": ["25µm LDPE", "5µm EVOH", "25µm LDPE"],
        "barrier_level": "Very High O2 Barrier / High Moisture",
        "sealability": "Excellent",
        "mechanical_strength": "High",
        "recyclability": "Recyclable (RIC #4 if EVOH < 5%)",
        "cost_category": "High",
        "temp_suitability": "Chilled / Frozen",
        "typical_applications": ["Fresh Meat MAP", "Cheese Trays", "Poultry Vacuum Skin"],
        "description": "Transparent high-barrier coextrusion locking gas flushes inside fresh meat and dairy pouches without metal foil."
    },
    {
        "id": "s-paper-pe",
        "code_name": "Kraft Paper / Extruded PE",
        "layer_composition": ["60gsm Virgin Kraft Paper", "15µm Extruded PE Sealant"],
        "barrier_level": "Moderate Moisture / Light Protection",
        "sealability": "Good",
        "mechanical_strength": "High Tear Resistance",
        "recyclability": "Paper Recyclable Stream",
        "cost_category": "Medium",
        "temp_suitability": "Ambient",
        "typical_applications": ["Flour", "Bulk Rice", "Artisanal Bread", "Organic Grains"],
        "description": "Sustainable paper laminate delivering natural organic aesthetic, structural stiffness, and moisture seal."
    }
]
